config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :quizzes
  resources :users
  resources :usergroups
  resources :posts
  resources :reacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :quiz

  has_many :posts
  has_many :usergroups
  has_many :users, through: :usergroups  
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :group
    has_many :reacts
    has_many :users, through: :reacts
end

app/models/quiz.rb
class Quiz < ApplicationRecord

    has_many :groups

end

app/models/react.rb
class React < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord

    has_many :usergroups
    has_many :groups, through: :usergroups

    has_many :reacts
    has_many :posts, through: :reacts
    
    has_secure_password

    validates :first_name, :last_name, :username, :email, :password, presence: true

end

app/models/usergroup.rb
class Usergroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in?, :current_user

    def logged_in?
      !session[:user_id].nil?
    end
  
    def current_user
      if logged_in?
        @current_user = User.find(session[:user_id])
      end
    end
  
    def authorized
      redirect_to "/login" unless logged_in?
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    def index
        @groups = Group.all
        @quizzes = Quiz.all
    end

    def show
        find_group
        @post = Post.new
    end

    def create
        @group = Group.create(group_params)
    end

    private

    def find_group
        @group = Group.find(params[:id])
    end

    def group_params
        params.require(:group).permit(:name, :bio, :quiz_id, post_ids:[])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end

    def create
        @post = Post.create(post_params)
        redirect_to post_path(@post)
    end

    def edit
        find_post
    end

    def update
        find_post
        @post.update(post_params)
        redirect_to post_path(@post)
    end

    def show
        find_post
    end

    def destroy
        find_post
        @group = @post.group
        @post.delete
        @post.save
        redirect_to "/groups/#{@group.id}"
    end

    private

    def find_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :content, :edit_status, :author, :group_id)
    end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

    def show
        find_quiz
    end

    private

    def find_quiz
        @quiz = Quiz.find(params[:id])
    end

    def quiz_params
        params.require(:quiz).permit(:name, :quiz_url, :quiz_website, :results_number, group_ids:[])
    end

end

app/controllers/reacts_controller.rb
class ReactsController < ApplicationController

    def create
        @react = React.create(react_params)
    end

    private

    def react_params
        params.require(:react).permit(:user_id, :post_id, :type, :completion)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      @user = User.find_by(email: params[:email])
    #   return head(:forbidden) unless @user.authenticate(params[:password])
    #   session[:user_id] = @user.id
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:notice] = "Either username or password is incorrect"
        render 'new'
      end
    end
  
    def destroy
      session.delete :user_id
      redirect_to "/login"
    end
  end

app/controllers/usergroups_controller.rb
class UsergroupsController < ApplicationController

    def create
        @usergroup = Usergroup.create(usergroup_params)
        redirect_to user_path(@usergroup.user)
    end

    private

    def usergroup_params
        params.require(:usergroup).permit(:user_id, :group_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authorized, only: [:show]

    def show
        find_user
        @quizzes = Quiz.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          flash[:error] = @user.errors.full_messages
          render 'new'
        end
    end

    def edit
        find_user
    end

    def update
        find_user
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    def destroy
        find_user
        @user.destroy
        redirect_to 
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :first_name, :last_name, :email, :id, :group_id, :password, :password_confirmation, :password_digest)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<h1> All Groups </h1>
<% @quizzes.each do |q| %>
<%# Quiz Header%>
    <h2> <%= q.name %> </h2>
    <%# Groups Based on Quiz Result %>
    <% q.groups.each do |g| %>
        <% if logged_in? %>
            <li> <%= link_to g.name, group_path(g) %> </li>
        <% else %>
            <li> <%= link_to g.name, "/login" %> </li>
        <% end %>
    <% end %>
<% end %> 

app/views/groups/show.html.erb
<h1> <%= @group.name %> </h1>
<ul>
    <li> Bio: <%= @group.bio %> </li>
    <li> Discord: <%= @group.discord_url %> </li>
    <li> Facebook: <%= @group.facebook_group_url %> </li>
    <li> Users:
        <ul>
            <% @group.users.each do |u| %>
                <%= link_to u.username, user_path(u) %>
            <% end %>
        </ul>
    </li>
    <li> Posts:
        <ul>
            <% @group.posts.each do |p| %>
                <br><%= link_to p.title + " - " + p.content , post_path(p) %></br>
            <% end %>
        </ul>
    </li>
</ul>


<% if current_user.groups.include?(@group) %>
<h3>Create New Post</h3>
    <%= form_for @post do |p| %>
        <%= p.hidden_field :user_id, value: current_user.id %>
        <%= p.hidden_field :group_id, value: @group.id %>
        <br> Title: <%= p.text_field :title %></br>
        <br> Content: <%= p.text_area :content %></br>
        <%= p.hidden_field :author, value: current_user.username %> </br>
        <br><%= p.submit %> </br>
    <% end %>
<% else %>
    You are not currently in this group
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <div class="row">
    <div class="col-sm">
      <% if logged_in? %>
        <%= link_to "User Page", user_path(current_user.id) %>
      <% elsif "/signup" %>
        <%= link_to "Login Page", "/login"%>
      <% end %>
    </div>
    <div class="col-sm">
      <%= link_to "Groups Page", groups_path %>
    </div>
    <div class="col-sm">
      <% if logged_in? %>
      <%= form_tag logout_path, method: "delete" do %>
        <%= submit_tag "Logout" %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h3> Edit Post</h3>
<%= form_for @post do |p| %>
    <%= p.hidden_field :user_id, value: current_user.id %>
    <%= p.hidden_field :group_id, value: @post.group_id %>
    <br> Title: <%= p.text_field :title, value: @post.title %></br>
    <br> Content: <%= p.text_area :content, value: @post.content %></br>
    <%= p.hidden_field :author, value: current_user.username %> </br>
    <br><%= p.submit %> </br>
<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.group.name %> - <%= @post.title %> </h1>
<p> <%= @post.content %> </p>
<% if current_user.username == @post.author %>
    <li> Written By: You </li>
    <%# Edit Post %>
    <h3> <%= link_to "Edit Post", "/posts/#{@post.id}/edit" %> </h3>
    <%# Delete Post %>
    <%= form_tag post_path(@post.id), method: "delete" do %>
        <%= submit_tag "Delete #{@post.title}" %>
    <% end %>
<% else %>
    <li> Written By: <%= @post.author %> </li> 
    <h3>React</h3>
    <%= form_for @post.reacts.build do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.submit "Like" %>
    <% end %>
    <%= "#{@post.reacts.count} likes" %>
<% end %>

app/views/quizzes/show.html.erb
<h1> <%= @quiz.name %> </h1>
<p> <%= link_to @quiz.quiz_url, @quiz.quiz_url %> </p>
<%= form_tag "/usergroups", method: "post" do %>
    <%= hidden_field_tag 'usergroup[user_id]', current_user.id %>
    <br> Result: <%= collection_select :usergroup, :group_id, @quiz.groups, :id,  :name %>
    <%= submit_tag 'Join Group' %> </br>
<% end %>

app/views/users/edit.html.erb
<h1> Edit User </h1>
<%= form_for @user do |u| %>
    <br> First Name: <%= u.text_field :first_name, value: @user.first_name %> </br>
    <br> Last Name: <%= u.text_field :last_name, value: @user.last_name %> </br>
    <br> Username: <%= u.text_field :username, value: @user.username %> </br>
    <br> Email: <%= u.email_field :email, value: @user.email %> </br>
    <br> Password: <%= u.password_field :password, value: @user.password_digest %> </br>
    <br> <%= u.submit %> </br>
<% end %>

app/views/users/new.html.erb
<% if flash[:error] %>
    <% flash[:error].each do |msg| %>
        <br> <%=  msg %> </br>
    <% end %>
<% end %>

<h1> Create New User </h1>
<%= form_for @user do |u| %>
    <br> First Name: <%= u.text_field :first_name %></br>
    <br> Last Name: <%= u.text_field :last_name %></br>
    <br> Username: <%= u.text_field :username %></br>
    <br> Email: <%= u.email_field :email %></br>
    <br> Password: <%= u.password_field :password %></br>
    <br> Password Confirmation: <%= u.password_field :password_confirmation %></br>
    <br><%= u.submit %> </br>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.first_name + " " + @user.last_name %></h1>
<ul> 
    <li> Username: <%= @user.username %> </li>
    <li> Email: <%= @user.email %> </li>
    <li> Groups:
        <ul>
            <% @user.groups.each do |g| %>
                <li> <%= link_to g.name, group_path(g) %> </li>
            <% end %>
        </ul>
    </li>
    <li> Take a Quiz:
        <ul>
            <% @quizzes.each do |q| %>
                <li> <%= link_to q.name, quiz_path(q) %> </li>
            <% end %>
        </ul>
    </li>
</ul>